name: Lightning_on_death
version: '${project.version}'
main: lightning_on_death.lightning_on_death.Lightning_on_death
api-version: 1.19
authors: [ Recho1235 ]
description: strikes lightning down on player position once they die
